version: "3.7"
services:
  app:
    image: node:lts
    working_dir: /usr/src/app
    tty: true
    ports:
      - 3000:3000
      - 6006:6006
    volumes:
      - ./:/usr/src/app
    #command: sh -c "yarn storybook"
    stdin_open: true
